const data = {
    products: [
        {
            _id: '1',
            name: 'Cleveland Train poster',
            category: 'poster',
            image: '/images/p1.jpg',
            price: 58,
            size: '20 x 30',
            rating: 4.5,
            numReviews: 10,
            description: '1930 Cleveland Train poster reprint',
        },
        {
            _id: '2',
            name: 'Cleveland map',
            category: 'map',
            image: '/images/p2.jpg',
            price: 78,
            size: '24 x 36',
            rating: 5.0,
            numReviews: 12,
            description: '1912 Cleveland map reprint',
        },
        {
            _id: '3',
            name: 'Manhattan Map',
            category: 'map',
            image: '/images/p3.jpg',
            price: 98,
            size: '16 x 48',
            rating: 5.0,
            numReviews: 90,
            description: 'Mid-century Manhattan Map reprint',
        },
        {
            _id: '4',
            name: 'World map',
            category: 'map',
            image: '/images/p4.jpg',
            price: 108,
            size: '30 x 40',
            rating: 5.0,
            numReviews: 30,
            description: '1912 World map reprint',
        },
        {
            _id: '5',
            name: 'Star chart',
            category: 'map',
            image: '/images/p5.jpg',
            price: 98,
            size: '24 x 36',
            rating: 5.0,
            numReviews: 100,
            description: '1810 Celestial Chart reprint',
        },
        {
            _id: '6',
            name: 'New York City subway',
            category: 'map',
            image: '/images/p1.jpg',
            price: 58,
            size: '20 x 30',
            rating: 5.0,
            numReviews: 101,
            description: 'Mid-century New York City subway',
        },
    ]
}
export default data;